version: '3'
services:
  contrihat:
    volumes:
      - '~/contrihat-config/:/root/contrihat-config/'
    build: .
    privileged: true
    logging:
      options:
        max-size: 500mb
    restart: unless-stopped
