version: '3'
services:
  contrihat:
    volumes:
      - '~/contrihat-config/:/root/contrihat-config/'
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    logging:
      options:
        max-size: 200mb
    restart: unless-stopped
